enum ErrorCode {
	SFTP_CONNECTION = 1000,
	SFTP_DOWNLOAD_FILE,
	ATDATA_INVALID_PIXEL_DATA,
	SEND_SQS_MESSAGE,
	DELETE_SQS_MESSAGE,
	ATDATA_PARSE_CSV_FILE,
	BIGBDM_ACCESS_TOKEN_API,
	BIGBDM_ACCESS_TOKEN_INVALID,
	BIGBDM_WEBSITE_ID_COLLECTION,
	INVALID_LINKEDIN_URL_API_INDEX,
	LINKEDIN_URL_API_ONE,
	LINKEDIN_URL_API_ALL,
	VETRIC_ENRICHMENT_API_ONE,
	VETRIC_ENRICHMENT_API_ALL,
	DYNAMODB_INVALID_ITEM,
	DYNAMODB_ACCESS,
	SLACK_SEND_MESSAGE,
}

export default ErrorCode;
