FROM node:20.12.0

RUN npm i -g pnpm@8.15.4

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/slack-webhook-register-function/package.json ./apps/slack-webhook-register-function/

RUN pnpm i -w
RUN pnpm --filter slack-webhook-register-function i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./apps/slack-webhook-register-function/ ./apps/slack-webhook-register-function/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@kynesis/slack-webhook-register-function"]
