FROM node:20.12.1

RUN npm i -g pnpm@8.15.5

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/common-functions-types/package.json ./packages/common-functions-types/

RUN pnpm i -w
RUN pnpm --filter common-functions-types i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./packages/common-functions-types/ ./packages/common-functions-types/

CMD ["pnpm", "exec", "nx", "start:dev", "@kynesis/common-functions-types"]