FROM node:20.11.1

RUN npm i -g pnpm@8.15.4

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/pixel-api/package.json ./apps/pixel-api/

RUN pnpm i -w
RUN pnpm --filter pixel-api i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./apps/pixel-api/ ./apps/pixel-api/

CMD ["pnpm", "exec", "nx", "start:dev", "@kynesis/pixel-api"]
