FROM node:20.11.1

RUN npm i -g pnpm@8.15.4

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/pixel-api-function/package.json ./apps/pixel-api-function/
COPY ./packages/common-functions-types/package.json ./packages/common-functions-types/

RUN pnpm i -w
RUN pnpm --filter pixel-api-function i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./apps/pixel-api-function/ ./apps/pixel-api-function/

CMD ["pnpm", "exec", "nx", "start:dev:docker", "@kynesis/pixel-api-function"]
