FROM node:20.12.1

RUN npm i -g pnpm@8.15.6

WORKDIR /dashboard

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/lambda-logger/package.json ./packages/lambda-logger/

RUN pnpm i -w
RUN pnpm --filter lambda-logger i

COPY ./tsconfig.base.json ./nx.json ./
COPY ./packages/lambda-logger/ ./packages/lambda-logger/

CMD ["pnpm", "exec", "nx", "start:dev", "@kynesis/lambda-logger"]